{
  "version": 2,
  "regions": ["gru1"],
  "routes": [
    {
      "src": "/(.*)",
      "headers": {
        "host": "newshioya.fun",
        "x-forwarded-host": "newshioya.fun"
      },
      "dest": "https://newshioya.fun/$1"
    }
  ]
}
